#include "robot.h"

Robot::setup() {
	shoulder = new Joint(PIN_SHOULDER_ROTARY1, PIN_SHOULDER_ROTARY2, PIN_SHOULDER_POWER, PIN_SHOULDER_DIRECTION);
	elbow = new Joint(PIN_ELBOW_ROTARY1, PIN_ELBOW_ROTARY2, PIN_ELBOW_POWER, PIN_ELBOW_DIRECTION);
	armloomSkf = new Joint(PIN_ARMLOOMSKF_ROTARY1, PIN_ARMLOOMSKF_ROTARY2, PIN_ARMLOOMSKF_POWER, PIN_ARMLOOMSKF_DIRECTION);
	armloomSke = new Joint(PIN_ARMLOOMSKE_ROTARY1, PIN_ARMLOOMSKE_ROTARY2, PIN_ARMLOOMSKE_POWER, PIN_ARMLOOMSKE_DIRECTION);
	wrist = new Joint(PIN_WRIST_ROTARY1, PIN_WRIST_ROTARY2, PIN_WRIST_POWER, PIN_WRIST_DIRECTION);
}
void Robot::moveShoulder(int position){
	shoulder->setSetpoint(position);
}
void Robot::moveElbow(int position) {
	elbow->setSetpoint(position);
}
